FROM node:18

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install
RUN npm install -g nodemon ts-node typescript

COPY . .

# Add execute permission to our init script
RUN chmod +x init-db.sh

EXPOSE 3000

CMD ["./init-db.sh"]